### ISSUE TITLE
nodemon index.js brandr-api-brandr-api-1  |  brandr-api-brandr-api-1  | sh: 1: nodemon: not found

### ISSUE THREAD

**Issue by josiahcoad** [ScientaNL/brandr-api#100]
just cloned your repo and ran `docker-compose -f docker-compose.local.yml up -d --force-recreate \  && docker-compose -f docker-compose.local.yml logs -f`

and got
brandr-api-brandr-api-1  | 
brandr-api-brandr-api-1  | > brandr-api@0.0.1 dev
brandr-api-brandr-api-1  | > nodemon index.js
brandr-api-brandr-api-1  | 
brandr-api-brandr-api-1  | sh: 1: nodemon: not found

**Comment by luukvhoudt** [comment]
Seems like `npm install` is required in the `app` directory in order to use `docker-compose.local.yml`. We recently added file this to simplify local development.

We should change back the code block in the "deploy" section of the README to use the `docker-compose.yml` file:

```shell
docker-compose -f docker-compose.yml up -d --force-recreate \
  && docker-compose -f docker-compose.yml logs -f
```

And we should add a new section "contributing" to the README with the `docker-compose.local.yml` file:

```shell
cd app && \
npm install && \
docker-compose -f docker-compose.local.yml up -d --force-recreate && \
docker-compose -f docker-compose.local.yml logs -f
```
